/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./../components/sections/AboutSection.vue')['default']
    AnimatedNumber: typeof import('./../components/common/AnimatedNumber.vue')['default']
    AppFooter: typeof import('./../components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/layout/AppHeader.vue')['default']
    BaseButton: typeof import('./../components/common/BaseButton.vue')['default']
    BaseCard: typeof import('./../components/common/BaseCard.vue')['default']
    BaseTag: typeof import('./../components/common/BaseTag.vue')['default']
    BrandMark: typeof import('./../components/layout/BrandMark.vue')['default']
    ContactSection: typeof import('./../components/sections/ContactSection.vue')['default']
    HeroSection: typeof import('./../components/sections/HeroSection.vue')['default']
    HeroVisual: typeof import('./../components/sections/HeroVisual.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    NowSection: typeof import('./../components/sections/NowSection.vue')['default']
    ProjectCard: typeof import('./../components/sections/ProjectCard.vue')['default']
    ProjectsSection: typeof import('./../components/sections/ProjectsSection.vue')['default']
    RevealMotion: typeof import('./../components/common/RevealMotion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionContainer: typeof import('./../components/common/SectionContainer.vue')['default']
    SectionHeader: typeof import('./../components/common/SectionHeader.vue')['default']
    StatsSection: typeof import('./../components/sections/StatsSection.vue')['default']
    TechSection: typeof import('./../components/sections/TechSection.vue')['default']
    TimelineSection: typeof import('./../components/sections/TimelineSection.vue')['default']
  }
}
